---

- name: Stop node application to clear up port 80 for certbot challenge
  shell:
    cmd: docker-compose stop
    chdir: "/home/{{ username }}/superset"

- name: Run certbot for SSL
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_create_if_missing: true
    certbot_admin_email: "{{ certbot_admin_email }}"
    certbot_certs:
      - domains:
          - "{{ fqdn }}"
    certbot_create_standalone_stop_services: []

- name: Move cert to certs
  command: cp /etc/letsencrypt/live/{{ fqdn }}/fullchain.pem /home/{{ username }}/superset/certs/fullchain.pem
  when: ssl_enable

- name: Move key to certs
  command: cp /etc/letsencrypt/live/{{ fqdn }}/privkey.pem /home/{{ username }}/superset/certs/privkey.pem
  when: ssl_enable

- name: Copy over nginx conf for SSL
  template:
    src: nginx.conf
    dest: "/home/{{ username }}/superset/nginx/nginx.conf"

- name: Copy over superset nginx conf for SSL
  template:
    src: superset.conf
    dest: "/home/{{ username }}/superset/nginx/superset.conf"
  notify:
    - restart docker-compose
