---

- name: Run certbot for SSL
  include_role:
    name: geerlingguy.certbot
  vars:
    certbot_create_if_missing: true
    certbot_admin_email: "{{ certbot_admin_email }}"
    certbot_certs:
      - domains:
          - "{{ fqdn }}"
    certbot_create_standalone_stop_services: []

- name: Copy over nginx conf for SSL
  template:
    src: nginx.conf
    dest: "/home/{{ username }}/superset/nginx/nginx.conf"

- name: Copy over superset nginx conf for SSL
  template:
    src: superset.conf
    dest: "/home/{{ username }}/superset/nginx/superset.conf"
  notify:
    - restart nginx
